### ISSUE TITLE
error: nix-shell requires a single derivation

### ISSUE THREAD

**Issue by agander** [alpmestan/ghc.nix#139]
I am trying to build ghc with nix.

My ghc repository is up to date.

I am running this:

```
$ nix-shell https://github.com/alpmestan/ghc.nix/archive/master.tar.gz
error: nix-shell requires a single derivation
Try 'nix-shell --help' for more information.
```
on ghc.nix commit: 133516af8426d775fa0dc75c787edd56299ee6cf

Its a while since I used it but then it worked.
Am I missing something?

**Comment by supersven** [comment]
Hm, looks like the documentation isn't correct after introducing flakes, @MangoIV ? :thinking: 

@agander , you may want to use the flake version instead:

```
nix develop github:alpmestan/ghc.nix
```

**Comment by agander** [comment]
Ok, will do.
Thanks @supersven

**Comment by MangoIV** [comment]
mmmh, this is weird, according to the documentation of `nix-shell`: 

> If path is not given, nix-shell defaults to shell.nix if it exists, and default.nix otherwise. 

As a `shell.nix` exists I don't really know why it tries to use the `default.nix`. If you invoke `nix-shell` locally in the repo of `ghc.nix`, it indeed correctly evaluates the `shell.nix`. I was assuming that when specifying the remote, it would also default to `shell.nix`, especially as it is not documented that it'd do otherwise, the more you know... I will fix the documentation or will restore the old behavior, namely `default.nix` to only provide one derivation, depending on what @alpmestan thinks about this. 

@agander for now you can use: 
`nix-shell https://github.com/alpmestan/ghc.nix/archive/master.tar.gz --attr outputs.devShells.x86_64-linux.default`

**Comment by MangoIV** [comment]
Explanation: `default.nix` now exposes the same interface as the `flake.nix`, the `shell.nix` exposes just `devShells.<currentSystem>.default` attr, before flakification the `default.nix` behaved like the `shell.nix` now which is the reason why it worked before. 

I'd like to reopen this issue as this is really a documentation issue and perhaps might even be considered a bug in nix (I think it should pick up the `shell.nix`)
