### ISSUE TITLE
mktexnam: Could not map source abbreviation  for phvr8t.

### ISSUE THREAD

**Issue by agander** [alpmestan/ghc.nix#14]
Whilst running:
`nix-shell ./ghc.nix/  --run 'hadrian/build.sh  docs'`

I get the following error:

Transcript written on Haddock.log.
shakeArgsWith   0.000s    0%
Function shake  0.328s   10%  ===
Database read   0.000s    0%
With database   0.000s    0%
Running rules   2.667s   89%  =========================
Total           2.995s  100%
Error when running Shake build system:
* docs
* _build/docs/pdfs/Haddock.pdf
user error (Development.Shake.cmd, system command failed
Command: /nix/store/p9zl3jj7gzwn11h4w8n46w9ql3df31d3-ghc-build-environment/bin/xelatex -halt-on-error Haddock.tex
Current directory: /run/user/1000/extra-dir-55140388394314
Exit code: 1
Stderr:
kpathsea: Running mktextfm phvr8t
/nix/store/qlrg74z2h0p8h5wb50l8rb6fvbyp6wwj-texlive-combined-2017/share/texmf/web2c/mktexnam: Could not map source abbreviation  for phvr8t.
/nix/store/qlrg74z2h0p8h5wb50l8rb6fvbyp6wwj-texlive-combined-2017/share/texmf/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input phvr8t
This is METAFONT, Version 2.7182818 (Web2C 2017/NixOS.org) (preloaded base=mf)

kpathsea: Running mktexmf phvr8t

! I can't find file `phvr8t'.
<*> ...:=ljfour; mag:=1; nonstopmode; input phvr8t

Please type another input file name
! Emergency stop.
<*> ...:=ljfour; mag:=1; nonstopmode; input phvr8t

Transcript written on mfput.log.
grep: phvr8t.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input phvr8t' failed to make phvr8t.tfm.
kpathsea: Appending font creation commands to missfont.log.
)

The full message is at: [](https://lpaste.net/2771067089258020864)

Q1: It says: "mktexnam: Need to update ?"
How {should,would} I do that?

I have zapped /nix after running `hadrian/build.sh -c -j`
But I this error before.
I have tried to locate 'phvr8t' and thought I found it in another texlive package.
I installed it but I wasnt able to enable it to be 'seen' by nix-shell/hadrian.

**Comment by agander** [comment]
The full message is at: [lpaste](https://lpaste.net/2771067089258020864)

**Comment by alpmestan** [comment]
Can you try: `nix-shell ./ghc.nix/ --pure --run 'hadrian/build.sh docs'` ?
Also, have you tried adding `phvr8t` (or whatever latex package that file is supposed to come from) [here](https://github.com/alpmestan/ghc.nix/blob/master/default.nix#L30) ?

**Comment by agander** [comment]
With `--pure` I get:
/home/gander/PROJ/haskell/ghc/hadrian/build.cabal.sh: line 36: type: cabal: not found
Please make sure 'cabal' is in your PATH

**Comment by agander** [comment]
> ... adding phvr8t (or whatever latex package...

Once its installed do I need to do/redo anything?

**Comment by alpmestan** [comment]
Just try again (without `--pure`).

**Comment by agander** [comment]
Ok, so this path? or derivation? (I'm not sure of nix terminology yet):
[tetex-texmf-3.0.tar.gz](https://github.com/NixOS/nixpkgs/tree/05d2a9efb5c927126e74b439bf3a6b26a1a4e7f6/pkgs/tools/typesetting/tex/tetex)
contains a tar ball containing a few 'phvr8t'.

Alp, any idea how to find which package this is in?

@warboys suggested nix-build instead of nix-env and then `find /nix ...` but I tried a few options to no avail.

(I dont really want to install it willy-nilly because I tried that and got in a pickle and had to delete /nix and start again)

**Comment by alpmestan** [comment]
@agander Perhaps [nix-index](https://github.com/bennofs/nix-index) could be useful for such a case?

**Comment by Warbo** [comment]
Hi @agander I got pinged from your mention. I'm not familiar with this project, but thought I'd try to help out.

The error message you're getting from (xe)latex looks like it's missing some packages. Taking a look in `ghc.nix/default.nix` I can see this line which is defining a self-contained set of latex packages, which I assume are the ones being used by your command:

```
nixpkgs.texlive.combine {
        inherit (nixpkgs.texlive) scheme-small collection-xetex fncychap titlesec tabulary varwidth framed capt-of wrapfig needspace dejavu-otf; };
```

Earlier in the file `nixpkgs` is defined as `import <nixpkgs> {}`, which is the normal way to load the set of definitions from the system's copy of the nixpkgs repository. The `nixpkgs.texlive.combine` function is creating a self-contained latex environment; the set of packages it's given (`scheme-small`, `collection-xetex`, etc.) are the packages that will be put in that environment. We probably need to add something to this set.

Googling for "phvr8t" I came across [this page](https://gist.github.com/fernandomantoan/3751190) which says that "phvr8t" might be provided by the "courier" or "helvetica" latex packages, or the "fonts extra" texlive package. Also [this result](http://rpmfind.net/linux/rpm2html/search.php?query=tex%28phvr8t.tfm%29) shows some redhat packages called "helvetic" (without the "a" at the end).

Armed with this information, I went to see what exists in `nixpkgs.texlive`. First I loaded `nix-repl` so I can evaluate Nix expressions:

```
$ nix-shell -p nix-repl --run nix-repl
nix-repl>
```

Next I imported nixpkgs just like `ghc.nix/default.nix` and looked at the value of `texlive`:

```
nix-repl> (import <nixpkgs> {}).texlive
{ "12many" = { ... }; "2up" = { ... }; Asana-Math = { ... }; ESIEEcv = { ... }; FAQ-en = { ... }; GS1 = { ... }; HA-prosper = { ... }; IEEEconf = { ... }; IEEEtran = { ... }; MemoirChapStyles = { ... }; SIstyle = { ... }; SIunits = { ... }; Tabbing = { ... }; Type1fonts = { ... }; a0poster = { ... }; a2ping = { ... }; a4wide = { ... }; a5comb = { ... }; aastex = { ... }; abbr = { ... }; abc = { ... }; abnt = { ... }; abntex2 = { ... }; abraces = { ... }; abstract = { ... }; abstyles = { ... };
...
```

This gave a lot of output, but I was able to search it since I'm running inside Emacs. If you're just using a simple terminal then you might want to send it to a file instead, and search in that file using a text editor, e.g.

```
$ echo '(import <nixpkgs> {}).texlive' | nix-shell -p nix-repl --run nix-repl > output_file 2>&1
```

Searching for "courier" found a matching entry called `courier`, so I looked that up in `nix-repl`:

```
nix-repl> (import <nixpkgs> {}).texlive.courier
{ pkgs = [ ... ]; }
```

This appears to be a set containing a `pkgs` entry, so I inspected that:

```
nix-repl> (import <nixpkgs> {}).texlive.courier.pkgs
[ «derivation /nix/store/hjjg3a3m7ynkjbj6ggwcbp8893b2w31x-courier-2017.drv» ]
```

This is a list containing a single "derivation" (AKA package). We can get the first element of a list using the `builtins.head` function:

```
nix-repl> builtins.head (import <nixpkgs> {}).texlive.courier.pkgs
«derivation /nix/store/hjjg3a3m7ynkjbj6ggwcbp8893b2w31x-courier-2017.drv»
```

Now we can use the `:b` prefix in `nix-repl` to build that package:

```
nix-repl> :b builtins.head (import <nixpkgs> {}).texlive.courier.pkgs
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
/nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017

this derivation produced the following outputs:
  out -> /nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017
```

It looks like I already have an identical build of this package on my system (otherwise it would have tried to download a pre-built binary from the binary cache, or build the package locally if it wasn't in the cache). Now that the package has been built we can look inside it to see if there's anything matching `phvr8t`:

```
$ find /nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017
/nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017
/nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017/tex
/nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017/tex/latex
/nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017/tex/latex/courier
/nix/store/99jf9rv1kw5vvhgmm19d4s5g36kri0kp-courier-2017/tex/latex/courier/ts1ucr.fd
...
```

Doing a quick search on these filenames doesn't find any matches. So I tried going through the same steps for "helvetica". It turns out that `nixpkgs.texlive` doesn't contain any entries matching "helvetica", but it *does* contain a `helvetic` entry! I looked it up in `nix-repl` in the same way:

```
nix-repl> builtins.head (import <nixpkgs> {}).texlive.helvetic.pkgs
«derivation /nix/store/frq7kfjm7mnhj1dp12c6cmnh7k6bj9gg-helvetic-2017.drv»

nix-repl> :b builtins.head (import <nixpkgs> {}).texlive.helvetic.pkgs
warning: you did not specify ‘--add-root’; the result might be removed by the garbage collector
/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017

this derivation produced the following outputs:
  out -> /nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017

nix-repl> 
$ find /nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017
/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017
/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017/tex
/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017/tex/latex
/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017/tex/latex/helvetic
/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017/tex/latex/helvetic/ts1uhv.fd
/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017/tex/latex/helvetic/omluhv.fd
...
```

Looking at the contents of this package, there *are* files matching `phvr8t`, including `/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017/fonts/vf/adobe/helvetic/phvr8t.vf` and `/nix/store/fdzm947fla184cshdp98jpqr7p3bs336-helvetic-2017/fonts/tfm/adobe/helvetic/phvr8t.tfm`.

So, it looks like adding the `helvetic` package to the list in `ghc.nix/default.nix` should fix this problem, and hopefully the steps I explained above will help clarify a little about how to use Nix, and help for future problems.

Also I'd point out that there shouldn't ever be a need to delete `/nix`, unless you want to stop using Nix completely. In fact you shouldn't ever change anything in there yourself, since Nix provides tools for managing it, e.g. `nix-store --delete`. Even then, there's usually no reason to delete things except to save space, and `nix-collect-garbage` will do that for you automatically.

**Comment by agander** [comment]
@Warbo: my sincerest apology, I have only just seen your very detailed response.
Thanks for taking the time - I shall digest...
